language: python
dist: trusty
sudo: required
python:
  - "2.7"
  - "3.5"
  - "3.6"
before_install:
  - sudo dpkg --add-architecture i386
  - sudo apt-get update
  - sudo apt-get install --no-install-recommends -y wine
  - pip install pytest pytest-cov codecov mock
install:
  - pip install -e .
script:
  - pytest --cov
after_success:
  - codecov
notifications:
  slack: climate-models:LuGwA2dGrgZRL1O7AssggqyP
