language: python
dist: trusty
sudo: required
python:
  - "3.5"
  - "3.6"
  - "3.7-dev"
before_install:
  - sudo dpkg --add-architecture i386
  - sudo apt-get update
  - sudo apt-get install --no-install-recommends -y wine
  - pip install pytest pytest-cov codecov mock nbval matplotlib goodtables git+https://github.com/thedataincubator/expectexception.git@master
install:
  - pip install -e .
script:
  - pytest --cov -rfsxEX
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then ./scripts/test_notebooks.sh; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then goodtables pymagicc/definitions/datapackage.json; fi
after_success:
  - codecov
