#language: python
sudo: true
dist: precise
before_install:
  - sudo dpkg --add-architecture i386
  - sudo apt-get update
  - sudo dpkg-query -l 'wine*'
  - sudo apt-get install wine:386
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install .
script:
  - python setup.py test
notifications:
  slack: climate-models:LuGwA2dGrgZRL1O7AssggqyP
