build: false

environment:
  matrix:
    - PYTHON: "C:\\Python37-x64"
      PYTHON_VERSION: "3.7"
      PYTHON_ARCH: "64"


init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - "%PYTHON%/Scripts/pip.exe install --upgrade pip --user"
  - "%PYTHON%/Scripts/pip.exe install .[tests]"

test_script:
  - "%PYTHON%/Scripts/pytest -rfsxEX tests"
