name: test-env-pymagicc
channels:
  - default
dependencies:
  - jupyter==1.0
  - pytest==3.1.3
  - matplotlib
  - pip:
    - "git+https://github.com/jhamrick/nbflow.git"
    - "git+https://github.com/thedataincubator/expectexception.git@master"
