docs_dir: docsrc
site_dir: docs
site_name: Pymagicc
nav:
  - Overview: index.md
  - Changelog: changelog.md
  - Developing: developing.md
  - File Conventions: file_conventions.md
  - pymagicc: pymagicc.md
  - pymagicc.api: pymagicc.api.md
  - pymagicc.io: pymagicc.io.md
  - pymagicc.config: pymagicc.config.md
theme: readthedocs
